Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Learn best practices for writing optimized SQL queries and improving database performance',1,'How to Write Efficient SQL Queries');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Understand the different types of SQL JOINs and how to use them effectively',1,'SQL JOINs Explained');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Learn the basics of indexing in SQL Server, including how to create and maintain indexes',1,'SQL Server Indexing Basics');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Understand the concept of stored procedures in SQL Server and learn how to create and use them',1,'SQL Server Stored Procedures');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Discover how to use functions in SQL Server to perform complex calculations and manipulations',1,'SQL Server Functions');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Learn how to create and use triggers in SQL Server to automate database operations',1,'SQL Server Triggers');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Understand the concept of transactions in SQL Server and how to use them for data consistency and integrity',1,'SQL Server Transactions');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Learn how to create and use views in SQL Server to simplify complex queries and improve database performance',1,'SQL Server Views');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Discover how to use Common Table Expressions (CTEs) in SQL Server to simplify complex queries and improve readability',1,'SQL Server Common Table Expressions');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Understand the different data types available in SQL Server and how to use them effectively',1,'SQL Server Data Types');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Learn how to create and use temporary tables in SQL Server for short-term data storage',1,'SQL Server Temporary Tables');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Discover best practices for designing and organizing SQL Server databases for maximum performance and scalability',1,'SQL Server Database Design');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Learn how to optimize SQL Server query performance by using indexes, statistics, and execution plans',1,'SQL Server Optimizing Query Performance');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Understand the different backup and recovery options in SQL Server and how to implement them',1,'SQL Server Backup and Recovery');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Discover how to secure SQL Server databases and protect sensitive data from unauthorized access',1,'SQL Server Security');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Learn how to use SQL Server Reporting Services (SSRS) to create and manage reports',1,'SQL Server Reporting Services');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Learn how to write basic Java programs, handle data types, and use various methods, classes and objects in Java.',1,'Java Tutorial for Beginners');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial explains how memory management works in Java, including garbage collection and the design of the heap.',1,'Understanding Java Memory Management');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial dives into details around creating, modifying and traversing Java arrays.',1,'Deep Dive into Java Arrays');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial introduces Java 8 streams and lambda expressions and how they can improve performance and code readability.',1,'Introducing Java 8 Streams and Lambdas');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('How annotations in Java work and why they are used.',1,'Java Annotations Explained');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of creating Java objects and understanding the fundamentals of object-oriented programming.',1,'Introduction to Object-Oriented Programming in Java');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of serialization in Java and its benefits.',1,'An Overview of Java Serialization');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of concurrency and thread safety in Java applications.',1,'Concurrency in Java');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers basics of creating RESTful APIs using the Spring framework.',1,'Creating RESTful APIs with Spring');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of authentication and authorization with the Spring framework.',1,'Using Spring Security for Authentication and Authorization');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of using Spring Data JPA to improve data access performance and provide advanced features such as caching and lazy loading.',1,'Introducing Spring Data JPA');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of writing SQL queries in Java and how they can be used to access data.',1,'Writing SQL Queries in Java');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of JDBC and how it can be used to integrate Java applications with databases.',1,'Understanding JDBC Fundamentals');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of design patterns and how they can be used to improve software design.',1,'Design Patterns with Java');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the memory model in Java and how it works.',1,'Understanding Java Memory Model');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of exception handling in Java and how it can be used to debug code.',1,'Exception Handling in Java');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers how annotations can be used with the Spring framework to simplify configuration.',1,'Using Annotations in Spring');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers how data access can be simplified with the Spring framework.',1,'Data Access with Spring');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of servlets in Java and how they can be used to create dynamic web applications.',1,'Java Servlet Basics');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of Spring Boot and how it can be used to quickly create web applications.',1,'Introduction to Spring Boot');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of transactions in Spring and how they can be used to ensure data integrity.',1,'Transactions in Spring');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of reactive programming in Java.',1,'Reactive Programming in Java');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of Spring MVC and how it can be used to create web applications.',1,'Spring Web MVC');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of Java Persistence API (JPA) and how it can be used with the Spring framework.',1,'Using JPA with Spring');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of aspect-oriented programming (AOP) and how it can be used with the Spring framework.',1,'Understanding AOP in Spring');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of testing Spring Boot applications and how it can be used to ensure code quality.',1,'Testing Spring Boot Applications');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of the microservices architecture and how it can be implemented with the Spring Boot framework.',1,'Spring Boot For Microservices');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of logging in Spring and how it can be used to debug applications.',1,'Logging with Spring');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of creating RESTful services with the Spring framework.',1,'RESTful Services with Spring');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of MongoDB and how it can be integrated with the Spring framework.',1,'Integrating Spring with MongoDB');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of Spring Profiles and how it can be used to manage application configurations.',1,'Spring Profiles');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of testing Spring Boot applications and how it can be used to ensure code quality.',1,'Spring Boot Testing');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of Spring Data Rest and how it can be used to quickly create CRUD APIs.',1,'Using Spring Data Rest');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('Learn the basics of SQL, including syntax, data types, and working with databases',1,'Introduction to SQL');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of performance and scalability in Spring and how it can be improved.',1,'Performance and Scalability in Spring');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of integrating Apache Kafka with the Spring framework.',1,'Spring Integration with Kafka');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the fundamentals of authentication and authorization in the Spring framework.',1,'Spring Security Fundamentals');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('This tutorial covers the basics of integrating the Hibernate ORM with the Spring framework.',1,'Spring ORM with Hibernate');
Insert into HR.TUTORIALS (DESCRIPTION,PUBLISHED,TITLE) values ('description 1',1,'title 1');